@ZeroStoreApp.CommandService_HostAddress = https://localhost:7100


### Create a new product

POST {{ZeroStoreApp.CommandService_HostAddress}}/api/product
Content-Type: application/json

{
  "name": "Product de Test",
  "description": "Product de test",
  "price": 5,
  "stock": 500
}

### update a product

PUT {{ZeroStoreApp.CommandService_HostAddress}}/api/product
Content-Type: application/json

{
    "id": "68834726-c0fc-4b17-e5ff-08dd51ca487f",
    "name": "Product de Test update",
    "description": "Product de test update",
    "price": 250,
    "stock": 250
  }

### delete a product (logical delete)

@productId = a4cb4ba1-1234-4431-466a-08dd4cacd7c6
DELETE {{ZeroStoreApp.CommandService_HostAddress}}/api/product/{{productId}}

###
